Implement video player
zyrouge/yukino-app pull request #184
Opened 2023-04-12 21:44 UTC by Foxify52

This is mostly finished but its not 100% complete. The actual call for the page needs to be added after the episode selector is added in the content page. I have left comments on both pages and also began cleaning up the content page in preparation for the episode list.

2023-04-13 00:30 UTC, Foxify52 commented
While I'm not sure of the functions of the provider file, it does seem to be pretty closely tied to video serving so I though I might as well include it too.

2023-09-06 14:13 UTC, zyrouge requested changes

2023-09-06 14:13 UTC, zyrouge commented on lib/ui/pages/anilist/components/body/login.dart
> +                    content: Text(err.toString()),
The previous was better.

2023-09-07 01:53 UTC, zyrouge approved these changes

2023-09-07 01:53 UTC, zyrouge commented
LGTM!

2023-09-07 01:53 UTC, merged